sonar.projectKey=bernardosvent_prova02-integration-tests-BernardoMarchioro
sonar.organization=bernardosvent
sonar.projectName=Jest Integration Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8

# Ignore missing assertion rule (S2699) in PactumJS tests since Sonar doesn't natively recognize Pactum's expectStatus, expectJson, etc.
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e1.resourceKey=test/**/*.ts